### ISSUE TITLE
AdultDVDEmpire Scraper not pulling images

### ISSUE THREAD

**Issue by JeepFiend** [xbmc-adult/xbmc-adult#44] opened 2015-05-07 23:46 UTC
Website changed content and the scraper no longer works.  Any chance of getting it updated to pull images now that they've added the preview feature that broke the plugin?

**Comment by mrdougquaid** [comment] 2015-05-11 13:29
Duplicate of #39

**Closed as completed by mrdougquaid** 2015-05-11 13:29 UTC
