### ISSUE TITLE
Site Not Working

### ISSUE THREAD

**Issue by Sameer888** [xbmc-adult/xbmc-adult#196] opened 2018-12-11 11:46 UTC
Please check that  porntrex,  Hq porner and Bitporno is not working

**Comment by Gujal00** [comment] 2018-12-11 23:44
Please check if bitporno is working on the browser. Looks like it is blocked by some ISPs. It is working fine for me.
nabil did the other two sites, I think he will get to them

**Comment by Sameer888** [comment] 2018-12-12 07:14
Yes Bitporno is working now ,thanks

**Comment by nabilbendafi** [comment] 2018-12-15 22:33
Duplicate of #195

**Closed as completed** 2018-12-16 05:23 UTC
