### ISSUE TITLE
Addon won't load on Android - script error with Future module

### ISSUE THREAD

**Issue by ghost** [xbmc-adult/xbmc-adult#346] opened 2020-05-02 02:12 UTC
Getting the following error with KODI on Android:

`Error Contents: (20, 'Not a directory', '/data/app/.../base.apk/assets/python2.7/lib/python2.7/lib2to3/Grammar.txt')
`
Seems the system cannot read Grammar.txt from within the .APK file on the Android filesystem.

A possible workaround would be on line 7 in videodevil.py:
```
[ORIGINAL]
from past.builtins import basestring

[MODIFIED]
try:
	from past.builtins import basestring
except:
	basestring = str
```

Thanks

**Comment by Gujal00** [comment] 2020-05-02 14:43
Duplicate of #324 
What are the versions of Android and Kodi?
Tested and found no issues on Android 9 with Kodi 18.6

**Comment by Lamoboy** [comment] 2020-05-08 07:42
This solution doesn’t work on iOS.

**Closed as completed** 2020-07-15 13:36 UTC
